# Generated by Django 5.0.3 on 2024-03-05 19:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('house', models.CharField(blank=True, max_length=255, null=True)),
                ('apartment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Электронная почта'), ('phone', 'Мобильный телефон')], max_length=5)),
                ('value', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('giver', models.CharField(max_length=255)),
                ('date_issued', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientWithSpouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField()),
                ('cur_work_exp', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=3, null=True)),
                ('type_education', models.CharField(blank=True, choices=[('secondary', 'Среднее'), ('secondarySpecial', 'Среднее специальное'), ('incompleteHigher', 'Незаконченное высшее'), ('higher', 'Высшее'), ('twoOrMoreHigher', 'Два и более высших образований'), ('academicDegree', 'Академическая степень')], max_length=20, null=True)),
                ('mon_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mon_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('living_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_living_address', to='core.address')),
                ('reg_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_reg_address', to='core.address')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_spouse', to='core.clientwithspouse')),
                ('passport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_passport', to='core.passport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChildClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientwithspouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunicationClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientwithspouse')),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.communication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientwithspouse')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, choices=[('main', 'Основная работа'), ('part-time', 'Частичная занятость')], max_length=20, null=True)),
                ('date_emp', models.DateField(blank=True, null=True)),
                ('date_dismissal', models.DateField(blank=True, null=True)),
                ('mon_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tin', models.CharField(blank=True, max_length=12, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('fact_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_fact_address', to='core.address')),
                ('jur_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_jur_address', to='core.address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientwithspouse')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
