# Generated by Django 5.0.3 on 2024-03-05 22:42

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clientwithspouse',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='clientwithspouse',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
